services:
  support-crew:
    build: .
    container_name: support_agent_system
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: >
      sh -c "until nc -z qdrant 6334; do echo 'Waiting for Qdrant...'; sleep 1; done; 
      java -jar app.jar"
    depends_on:
      - qdrant


  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
      - ./qdrant_config.yaml:/qdrant/config.yaml:z
    restart: always
    environment:
      - QDRANT__SERVICE__ENABLE_STATIC_CONTENT=1
